### ISSUE TITLE
Standalone Certificate

### ISSUE THREAD

**Issue by flocomkoko** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#368] opened 2018-04-24 14:59 UTC
Is it possible to request a standalone certificate for further use (in my case a simple Mail server), that is autorenewed by the nginx-letsencrypt container without spinning up an container, that is basically useless?
I was thinking of something like 
`docker exec nginx-letsencrypt /app/request....`
Parallel to this "standalone cert" i would like to use the complete functionality of this nice container including the proxy for other services (in my case for a simple wiki and a nextcloud instance).

**Comment by cphamlet** [comment] 2018-04-25 04:06
I would also like to know this.

**Comment by cphamlet** [comment] 2018-04-25 04:38
This docker container makes use of the simp_le client, a lightweight letsencrypt client. [https://github.com/zenhack/simp_le](https://github.com/zenhack/simp_le )

You can try running that command on start, and stick it in the auto renew code.

**Comment by buchdag** [comment] 2018-06-28 22:40
An **experimental** version of this feature inspired by @ymettier PR #220 has been added to `dev`.

[This instructions are here](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/wiki/Standalone-certificates-(beta)). Any feedback is welcome.

**Comment by ladrua** [comment] 2018-07-02 21:36
Just tested this feature, works like a charm. Personally really need this in production yesterday... 😺 
How are the changes to the letsencrypt_user_data file picked up/triggered though?

**Comment by buchdag** [comment] 2018-07-04 09:06
@ladrua for now they're not picked up at all, meaning you'll either have to

- wait for the next service loop execution (every hour)
- manually trigger it with `docker exec your-le-container /app/signal_le_service`

**Comment by ladrua** [comment] 2018-07-04 09:18
Thanks. Thats fine. I had some issues all of a sudden on a new build of dev, had to `RUN chmod +x /app/signal_le_service && chmod +x /app/letsencrypt_service` because I got Permission Error. Also after, the chalange configs are left behind in the conf.d(the `example.com-standalone.conf` folder, and we get errors due to double definition of hostnames(we have other configs for the actuall services).

**Comment by buchdag** [comment] 2018-07-04 19:02
@ladrua I pushed two more commits to `dev`. The missing `;` has been corrected and the challenge config should be correctly removed too. No idea where you permission issue came from, I'll have to take a look again.

**Comment by ladrua** [comment] 2018-07-05 09:34
@buchdag Thanks! I'll have a go later. Also, does it create the challenge configs even though renewal is not necessary? Must it? Just realized that this recreation happend every time(hour) the service was triggered. So if I manually deleted the standalone confs, they came back an hour later.

**Comment by ladrua** [comment] 2018-07-05 09:45
And another thought, how are we sure the challange configs are used in favour of the manual configs you have for the underlying services during renewal/generation? Do we need some sort of naming convention for the manual configs?

**Comment by buchdag** [comment] 2018-07-05 13:22
> does it create the challenge configs even though renewal is not necessary? Must it?

Yes, because `simp_le` is determining by itself if the certificate needs to be renewed or not, there is no "pre-renewal" hook we can use to create / change the challenge config only when a certificate is about to be created or renewed.

The situation is the same for the certificate that are created from containers environment variables, [`add_location_configuration`](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/90eaa8c952a6858b03c7316ceffa1818eb083744/app/functions.sh#L26) is executed every hour for every domain, wether a certificate is going to be created/renewed or not.

> how are we sure the challange configs are used in favour of the manual configs you have for the underlying services during renewal/generation?

I can't answer with certainty yet, that's why this feature is considered experimental for now.

**Comment by ladrua** [comment] 2018-07-06 09:35
I see, I guess there must be a naming convention for the standalone configs(maybe matching the LETSENCRYPT_STANDALONE_CERTS array defeintions?), and the service disable/re-enable them somehow?

**Comment by ladrua** [comment] 2018-07-06 09:40
Just did a rebuild, I now get this error from docker logs `unknown log format "vhost" in /etc/nginx/conf.d/example.com-standalone-cert.conf:4`

**Comment by buchdag** [comment] 2018-07-06 10:09
I've pushed a new commit with the `vhost` logging format defined directly in the challenge config file, that should fix that logging error.

> I see, I guess there must be a naming convention for the standalone configs(maybe matching the LETSENCRYPT_STANDALONE_CERTS array defeintions?), and the service disable/re-enable them somehow?

The expected behavior is (no matter what happen to the certificate):
- create required standalone config files
- reload nginx
- let simp_le create / renew / do nothing
- remove standalone config files
- reload nginx

No idea why `simp_le` crashed like that, I did not touch anything that effect the `simp_le` process. The only relevant issue I found is this one on another repo : https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/issues/62

**Comment by ladrua** [comment] 2018-07-06 10:13
Sorry, I did update my comment a bit with a bit more detailed information.

**Comment by ladrua** [comment] 2018-07-06 10:43
I think you need to remove the fix for the `vhost` log_format, as I now get `duplicate "log_format" name "vhost" in /etc/nginx/conf.d/default.conf:31` and I am pretty sure it happened because of my domain name starting with `da` and hence the config is loaded before the `default.conf` Not sure how to solve that though.

**Comment by ladrua** [comment] 2018-07-06 10:50
It still leaves my `example.com-standalone-cert.conf` it might be because the second domain `example2.com` fails?

```
/etc/nginx/certs/example.com /app
Creating/renewal example.com certificates... (example.com)
2018-07-06 10:39:58,610:INFO:simp_le:1564: Certificates already exist and renewal is not necessary, exiting with status code 1.
/app
/etc/nginx/certs/example2.com /app
Creating/renewal example2.com certificates... (example2.com)
2018-07-06 10:40:00,421:INFO:simp_le:1479: Generating new certificate private key
2018-07-06 10:40:02,160:ERROR:simp_le:1446: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/BG_wfHlxgf2zf3W0SKzcCBeapDFGszBU56tGoH7Hdp0
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1584, in main
    return main_with_exceptions(cli_args)
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1567, in main_with_exceptions
    persist_new_data(args, existing_data)
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1489, in persist_new_data
    account_key=client.key, key=None, cert=None, chain=None))
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1195, in persist_data
    plugin.save(new_data)
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 493, in save
    key = self.dump_key(data.key)
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 436, in dump_key
    return OpenSSL.crypto.dump_privatekey(self.typ, data.wrapped).strip()
AttributeError: 'NoneType' object has no attribute 'wrapped'

Unhandled error has happened, traceback is above

Debugging tips: -v improves output verbosity. Help is available under --help.
/app
Reloading nginx proxy (f6a4d720ab48f26ccb1f6ff5ae2b388579098f1547f7b98198123616f6fd3c89)...
2Custom dhparam.pem file found, generation skipped
h2018/07/06 10:40:02 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
�2018/07/06 10:40:02 [emerg] 3929#3929: duplicate "log_format" name "vhost" in /etc/nginx/conf.d/default.conf:31
nginx: [emerg] duplicate "log_format" name "vhost" in /etc/nginx/conf.d/default.conf:31
```

**Comment by buchdag** [comment] 2018-07-06 12:09
> I think you need to remove the fix for the vhost log_format

Done. I also changed the test unit slightly to cover making change to `letsencrypt_user_data` and manually triggering of the service loop to pick up those changes.

> it happened because of my domain name starting with `da` and hence the config is loaded before the `default.conf` Not sure how to solve that though.

The most straightforward and simple solution is probably just to name the config file `standalone-cert-$domain.conf` instead of `$domain-standalone-cert.conf`. This change has been committed to `dev`.

> It still leaves my `example.com-standalone-cert.conf` it might be because the second domain `example2.com` fails?

Could you try to remove the certificate covering the domain whose challenge is failing from `letsencrypt_user_data` ?

**Comment by ladrua** [comment] 2018-07-31 06:00
Looks good to me with the latest changes, but the change of name convention to `standalone-cert-$domain.conf` would not work for say.. xxx.com.

**Comment by buchdag** [comment] 2018-08-01 12:55
> but the change of name convention to `standalone-cert-$domain.conf` would not work for say.. xxx.com

I don't understand why it would not work, "working" here being the domain specific, self generated conf file loading after `default.conf` no matter what the domain is.

Unless I'm mistaken, a conf file starting with an `s` will always load after a conf file starting with a `d`.

**Comment by buchdag** [comment] 2018-08-20 15:06
@ymettier @mossholderm @ryneeverett @ForsakenHarmony @augusteo @Pimmetje @hamon-e @Panderine @CWempe @flocomkoko @cphamlet @hadrien-toma @kosli @VeeeneX @felixsteghofer @curtiszimmerman

You manifested interest at some point for the ability to generate "standalone" certificates with letsencrypt-nginx-proxy-companion (ie certificate not created from a Docker container environment variables). A beta version of this feature, inspired by @ymettier #220 has been merged to the `dev` branch and is available through Docker hub with the `dev` tagged version of this container.

Instructions are here : https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/wiki/Standalone-certificates-(beta)

If you are still using letsencrypt-nginx-proxy-companion and are still interested by this feature, test and feedback would be super helpful.

Sorry in advance if the mention for an old topic bothered you.

**Comment by curtiszimmerman** [comment] 2018-08-20 15:18
Cool! I have use cases for this, and some of them are weird edge cases. Thanks for the tag! I'll check it out.

**Comment by ladrua** [comment] 2018-08-22 10:48
@buchdag I just updated with the docker image, and I am still having issue that the standalone-cert*.conf files are beeing created at every check, and then not removed in conf.d folder. Casuing problems with overriding some of my configs that are imported after the conf.d import. Other then that, it is working great!

**Comment by buchdag** [comment] 2018-08-22 11:45
That's weird, I've tried adding [special checks for that in the test unit](https://github.com/buchdag/docker-letsencrypt-nginx-proxy-companion/commit/b6af199729c97aea84d1bf22f6322e0091236f71), and [the resulting build pass without issues](https://travis-ci.org/buchdag/docker-letsencrypt-nginx-proxy-companion/builds/419126141). Are you sure you pulled or build an up to date version and those aren't leftovers files from a previous `dev` version ?

**Comment by buchdag** [comment] 2018-08-22 13:07
I updated the `dev` image to track changes in `latest` + the following changes:

- `/etc/nginx/conf.d` presence and writeability is now checked once during container init with the existing `check_writable_directory` function
- any remaining standalone configuration files are cleaned up on container exit
- added the previously mentioned check to the `certs_standalone` test unit
- added an additional debug message when standalone configuration files are deleted during the LE service loop

**Comment by ladrua** [comment] 2018-08-23 15:05
@buchdag I cant actually be sure that they werent left there from previous build. Will try and do some more tests this evening. Thank you!

**Comment by buchdag** [comment] 2018-08-23 23:01
@ladrua the `for` loop that handle standlone config removal was at the wrong level, that should finally be fixed in the latest `dev` version.

**Comment by ladrua** [comment] 2018-08-31 10:40
I can confirm that its working as expected now. Have it running on two different live environments, and its looking good so far.

**Comment by buchdag** [comment] 2018-11-23 21:12
Anything else to report from people who tested this feature ?

I'm considering it for merging into the master branch in the coming weeks.

**Comment by ladrua** [comment] 2018-11-24 00:39
All I can say is that I've been running them since I last mentioned it, in two production environments,  without any issues.

**Comment by Gaibhne** [comment] 2020-01-30 14:10
The patch for this in the `dev` branch does not work anymore, because the current nginx images don't run as root anymore, making it necessary to run on a 1024+ port. Unfortunately, port 80 is hard coded in [`functions.sh#L109`](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blame/2c42e9394910e41e0db1ee3244c6de1957888255/app/functions.sh#L109). Of course it is relatively trivial to change yourself to a different port and recompile the image, but I would suggest a config parameter to allow for a more convenient usage.

**Comment by buchdag** [comment] 2020-02-01 10:44
> The patch for this in the `dev` branch does not work anymore.

Yet the test [still passes](https://travis-ci.org/JrCs/docker-letsencrypt-nginx-proxy-companion/builds/644719096) using the latest `nginx:alpine`.

As far as I can tell the current nginx images [are still listening on port 80](https://github.com/nginxinc/docker-nginx/blob/5971de30c487356d5d2a2e1a79e02b2612f9a72f/mainline/buster/Dockerfile#L99).

Could you provide more info about the issue you are experiencing ?

**Closed** 2020-05-11 14:43 UTC
Labels: Enhancement

**Comment by buchdag** [comment] 2020-05-11 15:07
Sorry it took soooooo long to merge but this feature is now in `lastest`
