### ISSUE TITLE
acme.sh: command not found

### ISSUE THREAD

**Issue by sparx82** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#737] opened 2020-12-21 21:52 UTC
Hi All,

I'm using the `latest` version of `docker-letsencrypt-nginx-proxy-companion` from Dockerhub and have the follwing error when starting up:

```
calling acme.sh --register-account with the following parameters : --log /dev/null --debug 2 --server https://acme-v02.api.letsencrypt.org/directory --config-home /etc/acme.sh/xyz@xyz.com --accountemail xyz@xyz.com
/app/letsencrypt_service: line 265: acme.sh: command not found
grep: /etc/acme.sh/xyz@xyz.com/ca/acme-v02.api.letsencrypt.org/account.json: No such file or directory
```

Everything worked fine when I used a previous version which didn't use acme. When I bash into the container I see that /app/acme.sh is there and executable.

What could be wrong?

Best regards,
Oliver

**Comment by sparx82** [comment] 2020-12-21 21:57
Docker image has this command:

`
ENV COMPANION_VERSION=v2.0.1-6-ga717c35 DOCKER_HOST=unix:///var/run/docker.sock PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/app
`

But $PATH outputs this:

`bash-5.0# $PATH
bash: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin: No such file or directory
`

**Comment by buchdag** [comment] 2020-12-21 22:03
Duplicate of #732

**Comment by buchdag** [comment] 2020-12-21 22:17
@sparx82 @XanderStrike any idea why the $PATH might not work inside your containers ? The fact that the CI is still passing means it's working properly in some cases and not in others.

**Comment by sparx82** [comment] 2020-12-22 06:27
I use Portainer as a docker management system. The ENV Path was defined like this:

![image](https://user-images.githubusercontent.com/17567952/102856531-f41e3b00-4426-11eb-96ac-c4098abdec96.png)

And when I add `/app`, everything works:

![image](https://user-images.githubusercontent.com/17567952/102856608-16b05400-4427-11eb-9346-8b4a38c75302.png)

**Comment by XanderStrike** [comment] 2020-12-24 00:02
I also use Portainer, interesting! Did you update it using Portainer? That's what I did, I wonder if it clobbered the changes to PATH.

I resolved my issue by starting over from scratch (deleting everything including the volume, reinstalling from the readme in this repo) and letting it generate all new certs. This only resulted in a few minutes downtime for my ~50 sites which isn't too bad at all.

**Comment by buchdag** [comment] 2020-12-24 08:58
From #732:

> Based on the other issue I suspect this was a PATH problem caused by Portainer's upgrade feature that keeps environment variables while changing the container image.

@XanderStrike that seems likely. Is there a way to set a custom PATH in a Docker image that won't interfere with this feature of Portainer ?

**Comment by sparx82** [comment] 2020-12-26 20:34
> Did you update it using Portainer?

Yes, I used "Recreate" and switched on the "Pull latest image". And I was on "latest", it pulled that one. I guess it did not update the PATH using this method.

**Comment by XanderStrike** [comment] 2020-12-26 21:39
Well that settles it then!

> Is there a way to set a custom PATH in a Docker image that won't interfere with this feature of Portainer ?

I've done some experimenting and Portainer seems to pull all environment variables out of the Dockerfile and sets them in stone forever. 

I don't think there's anything for this project to do, definitely seems like a bug or at least bad behavior with Portainer. I've created an issue to get their thoughts here: https://github.com/portainer/portainer/issues/4665

**Comment by buchdag** [comment] 2021-01-14 22:04
Given the answer received by @XanderStrike in https://github.com/portainer/portainer/issues/4665, I'm going to remove the `bug` label and close this issue. If Portainer isn't disposed to discriminate between image's default environment variable and user set environment variable, I'm not disposed to accommodate Portainer non standard way of creating containers either.

**Closed by buchdag** 2021-01-14 22:04 UTC
Labels: Question
