### ISSUE TITLE
Unable to obtain certificate.

### ISSUE THREAD

**Issue by KeironO** [nginx-proxy/docker-letsencrypt-nginx-proxy-companion#651] opened 2020-05-06 19:34 UTC
I get the following error if I attempt to use this tool:

```
limbus@docker-s-1vcpu-1gb-lon1-01:~/limbus$ docker logs nginx-ssl
Info: Custom Diffie-Hellman group found, generation skipped.
Reloading nginx proxy (f511cb0bdfe0d5a9777d9a46a4ca29d089b67d82d6db239179c673d4ff2698e9)...
2020/05/06 19:32:54 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
2020/05/06 19:32:54 [notice] 96#96: signal process started
Sleep for 3600s
2020/05/06 19:32:55 Generated '/app/letsencrypt_service_data' from 4 containers
2020/05/06 19:32:55 Running '/app/signal_le_service'
2020/05/06 19:32:55 Watching docker events
2020/05/06 19:32:55 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
/etc/nginx/certs/limbus.abersystemsbiology.co.uk /app
Reloading nginx proxy (f511cb0bdfe0d5a9777d9a46a4ca29d089b67d82d6db239179c673d4ff2698e9)...
2020/05/06 19:32:55 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
2020/05/06 19:32:55 [notice] 117#117: signal process started
Creating/renewal limbus.abersystemsbiology.co.uk certificates... (limbus.abersystemsbiology.co.uk)
2020-05-06 19:32:57,108:INFO:simp_le:1359: Generating new account key
2020-05-06 19:32:58,362:INFO:simp_le:1387: By using simp_le, you implicitly agree to the CA's terms of service: https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
2020-05-06 19:32:58,650:INFO:simp_le:1450: Generating new certificate private key
2020-05-06 19:33:11,739:ERROR:simp_le:1417: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v02.api.letsencrypt.org/acme/authz-v3/4409309600
2020-05-06 19:33:11,742:INFO:simp_le:401: Saving account_key.json
2020-05-06 19:33:11,743:INFO:simp_le:401: Saving account_reg.json
Challenge validation has failed, see error log.

Debugging tips: -v improves output verbosity. Help is available under --help.
/app
/etc/nginx/certs/limbus.abersystemsbiology.co.uk /app
Creating/renewal limbus.abersystemsbiology.co.uk certificates... (limbus.abersystemsbiology.co.uk)
2020-05-06 19:33:12,857:INFO:simp_le:1450: Generating new certificate private key
2020-05-06 19:33:24,973:ERROR:simp_le:1417: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v02.api.letsencrypt.org/acme/authz-v3/4409313703
Challenge validation has failed, see error log.
```

My dockerfile looks like:

```
version: "3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./services/certs:/etc/nginx/certs
      - ./services/htpasswd:/etc/nginx/htpasswd
      - ./services/nginx/html:/usr/share/nginx/html
      - ./services/nginx/vhost.d:/etc/nginx/vhost.d
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    networks:
      - nginx

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-ssl
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./services/certs:/etc/nginx/certs
      - ./services/htpasswd:/etc/nginx/htpasswd
      - ./services/nginx/html:/usr/share/nginx/html
      - ./services/nginx/vhost.d:/etc/nginx/vhost.d
    links:
      - nginx-proxy
    depends_on:
      - nginx-proxy
    networks:
      - nginx
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    volumes:
      - ./services/web/:/limbus/
    expose:
      - 5000
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      .env

    command: venv/bin/gunicorn --bind 0.0.0.0:5000 run:app
  db:
    image: postgres:10
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

networks:
  nginx:
    external: true

volumes:
  postgres_data:

```

**Comment by KeironO** [comment] 2020-05-06 19:39
```

**Comment by mat-l** [comment] 2020-05-07 08:13
I have a similar/the same problem with the docker version of nginx-proxy-letsencrypt. Maybe the additional logs are helping:

>     resp = conn.urlopen(,
>   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen,
>     retries = retries.increment(,
>   File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment,
>     raise MaxRetryError(_pool, url, error or ResponseError(cause)),
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe4f6a664c0>: Failed to establish a new connection: [Errno -3] Try again')),
> ,
> During handling of the above exception, another exception occurred:,
> Traceback (most recent call last):,
>   File "/usr/lib/python3.8/site-packages/simp_le.py", line 1601, in main,
>     return main_with_exceptions(cli_args),
>   File "/usr/lib/python3.8/site-packages/simp_le.py", line 1585, in main_with_exceptions,
>     persist_new_data(args, existing_data),
>   File "/usr/lib/python3.8/site-packages/simp_le.py", line 1443, in persist_new_data,
>     client = registered_client(,
>   File "/usr/lib/python3.8/site-packages/simp_le.py", line 1377, in registered_client,
>     directory = messages.Directory.from_json(net.get(args.server).json()),
>   File "/usr/lib/python3.8/site-packages/acme/client.py", line 1141, in get,
>     self._send_request('GET', url, **kwargs), content_type=content_type),
>   File "/usr/lib/python3.8/site-packages/acme/client.py", line 1091, in _send_request,
>     response = self.session.request(method, url, *args, **kwargs),
>   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request,
>     resp = self.send(prep, **send_kwargs),
>   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send,
>     r = adapter.send(request, **kwargs),
>   File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 516, in send,
>     raise ConnectionError(e, request=request),
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe4f6a664c0>: Failed to establish a new connection: [Errno -3] Try again')),
> Unhandled error has happened, traceback is above,
> Debugging tips: -v improves output verbosity. Help is available under --help.,
> /app,
> /etc/nginx/certs/tld /app,
> Creating/renewal tld certificates... (tld),
> 2020-05-07 08:03:08,684:INFO:simp_le:1359: Generating new account key,
>     conn = connection.create_connection(,
>   File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 156, in _new_conn,
>   File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection,
>     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):,
>   File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo,
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):,
> socket.gaierror: [Errno -3] Try again,
>   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen,
>     httplib_response = self._make_request(,
>     self._validate_conn(conn),
>   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 376, in _make_request,
>   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn,
>     conn.connect(),
>     conn = self._new_conn(),
>   File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 300, in connect,
>   File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 168, in _new_conn,
>     raise NewConnectionError(,
> urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fd2dc490820>: Failed to establish a new connection: [Errno -3] Try again,
>   File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send,
>     resp = conn.urlopen(,
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd2dc490820>: Failed to establish a new connection: [Errno -3] Try again')),
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd2dc490820>: Failed to establish a new connection: [Errno -3] Try again')),
> Sleep for 3600s

**Comment by buchdag** [comment] 2020-05-07 12:34
@KeironO please have a look at https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Invalid-authorizations.md

Additionally you have a link the failing auth in the error log for more informations. Yours says that the ACME validation server got a 503 when trying to fetch the challenge file from your domain.

@mat-l your issue is different and is caused by `simp_le` failing to connect to https://acme-v02.api.letsencrypt.org, please have a look at #631

**Comment by sosukeinu** [comment] 2020-05-18 18:27
I am also having the same issue as @KeironO. I have read https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Invalid-authorizations.md, and enabled debug. The relevant portion of my logs are below:

```
2020-05-18 18:10:07,185:DEBUG:acme.client:1102: Sending POST request to https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/57595483:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS1zdGFnaW5nLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYWNjdC8xMzc0Mjk5NiIsICJub25jZSI6ICIwMDAxYVJ5MlZEYUxTMDRZY
XJjLUY0TnVMc2VzaV9IalFpREdfWWJZbDE2UFVRNCIsICJ1cmwiOiAiaHR0cHM6Ly9hY21lLXN0YWdpbmctdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My81NzU5NTQ4MyJ9",
  "signature": "HBZ-2lgBLzBAnoiFhStjMACkpw7bAB1Xenb4msUoFYLAAXUQXoXcibKYiOm9SKTKdHaQ3I8vOWsmKbUtLGXTLdNNrH5aSbCCeIEcfZGNJtg5-5M0gExvv_ch7l6AxLBwZ4dPeDWvILCubs5YH-g03otRt8LOL
4hqmj_FwIxtlHt-FWuOup3eMWMbYaUx1jOaHRsXc9uOgYz8I9STPP3qkA6COnP3hGoCTDZfMX8M2RQfHd0f-bJJYXo-I32wyhvVcWlMr5PwDy6f8hi6sQYJ_8q8jTQLIf-AbXEduaAZmoogdE73shBh1lHW0-ocrLXhdayxVpAk1v
CY8P1R5E7-_PUhB-GgVecBzo0jKR-TE2C-WN92pM8_9TXnQgq3GOvCnqOv8ZFpuuFVL8uBIYHS5WIvpCf7PQ7jSWMBz_v73QVMaiWs2ZTMxUL40kdBFVbj-he9Z1Ydeu5252QdZK6aLF4AnNsCUfuyeunms1J4ojn_EF_0lxqp3DB
rRNT2d-pbLKcVXFl6Abw7t9zGXHKa52__e162jdTedC-4msq18qblHisgzsCYtSFxva7mYEodIQTF9pdjtYAzmOBc6OX9AN9VB1j-rpv45Q6OZkX7jf5fH6C20mEpjRxLGRDue4VxA6RsTumKmeeVXFI1UtmzJa8DTB8QijYIcelA
VK1AVnI",
  "payload": ""
}
2020-05-18 18:10:07,248:DEBUG:urllib3.connectionpool:437: https://acme-staging-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/57595483 HTTP/1.1" 200 1301
2020-05-18 18:10:07,250:DEBUG:acme.client:1145: Received response:
HTTP 200                                                                                                                                                                     
Server: nginx                                                                                                                                                                
Date: Mon, 18 May 2020 18:10:07 GMT                                                                                                                                          
Content-Type: application/json                                                                                                                                               
Content-Length: 1301                                                                                                                                                         
Connection: keep-alive                                                                                                                                                       
Boulder-Requester: 13742996                                                                                                                                                  
Cache-Control: public, max-age=0, no-cache                                                                                                                                   
Link: <https://acme-staging-v02.api.letsencrypt.org/directory>;rel="index"                                                                                                   
Replay-Nonce: 00023X_fu6szDFRU3VHPGyDMdgLUl3tqlUVg5Bmbc-CFeU4                                                                                                                
X-Frame-Options: DENY                                                                                                                                                        
Strict-Transport-Security: max-age=604800                                                                                                                                    
                                                                                                                                                                             
{                                                                                                                                                                            
  "identifier": {                                                                                                                                                            
    "type": "dns",                                                                                                                                                           
    "value": "mydomain"                                                                                                                                    
  },                                                                                                                                                                         
  "status": "invalid",                                                                                                                                                       
  "expires": "2020-05-25T18:10:05Z",                                                                                                                                         
  "challenges": [                                                                                                                                                            
    {                                                                                                                                                                        
      "type": "http-01",                                                                                                                                                     
      "status": "invalid",                                                                                                                                                   
      "error": {                                                                                                                                                             
        "type": "urn:ietf:params:acme:error:unauthorized",                                                                                                                   
        "detail": "Invalid response from http://mydomain/.well-known/acme-challenge/NhRLAy2VcaZrjbhwSzVcE2DmUZMA42G5fQnzGIiW7do [161.35.99.16]: \"\u003chtml\u003e\\r\\n\u003chead\u003e\u003ctitle\u003e404 Not Found\u003c/title\u003e\u003c/head\u003e\\r\\n\u003cbody\u003e\\r\\n\u003ccenter\u003e\u003ch1\u003e404 Not Found\u003c/h1\u003e\u003c/center\u003e\\r\\n\u003chr\u003e\u003ccenter\u003enginx/1.17.6\u003c/ce\"",
        "status": 403
      },
      "url": "https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/57595483/1s01Qw",
      "token": "NhRLAy2VcaZrjbhwSzVcE2DmUZMA42G5fQnzGIiW7do",
      "validationRecord": [
         {
          "url": "http://mydomain/.well-known/acme-challenge/NhRLAy2VcaZrjbhwSzVcE2DmUZMA42G5fQnzGIiW7do",
          "hostname": "mydomain",
          "port": "80",
          "addressesResolved": [
            "myip"
          ],
          "addressUsed": "myip"
        }
      ]
    }
  ]
}
2020-05-18 18:10:07,253:DEBUG:acme.client:1170: Storing nonce: 00023X_fu6szDFRU3VHPGyDMdgLUl3tqlUVg5Bmbc-CFeU4
2020-05-18 18:10:07,254:ERROR:simp_le:1396: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-chall
enge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your ho
st's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge v
alidation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.
org/docs/caa/). Failing authorizations: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/57595483
2020-05-18 18:10:07,258:INFO:simp_le:396: Saving account_key.json
2020-05-18 18:10:07,259:INFO:simp_le:396: Saving account_reg.json
2020-05-18 18:10:07,260:DEBUG:simp_le:1098: Removing validation file at /usr/share/nginx/html/.well-known/acme-challenge/NhRLAy2VcaZrjbhwSzVcE2DmUZMA42G5fQnzGIiW7do
Challenge validation has failed, see error log.
```
My docker-compose.yml is as below:

```
version: '3.7'
services:
  nginx-reverse-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${CONFIG}/nginx/certs:/etc/nginx/certs:ro"
      - "${CONFIG}/nginx/vhost.d:/etc/nginx/vhost.d"
      - "${CONFIG}/nginx/nginx_proxy.conf:/etc/nginx/conf.d/nginx_proxy.conf:ro"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    environment:
      - "DEFAULT_HOST=${DOMAIN}.${TOP_LEVEL_DOMAIN}"
      - "DHPARAM_GENERATION=false"
    tty: true
    restart: unless-stopped

  letsencrypt-sidecar:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.12.1
    volumes:
      - "${CONFIG}/nginx/certs:/etc/nginx/certs"
      - "${CONFIG}/nginx/vhost.d:/etc/nginx/vhost.d"
      - "${CONFIG}/nginx/nginx_proxy.conf:/etc/nginx/conf.d/nginx_proxy.conf"
      - "${SITE}:/usr/share/nginx/html"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - "DEFAULT_EMAIL=info@${DOMAIN}.${TOP_LEVEL_DOMAIN}"
      - "NGINX_PROXY_CONTAINER=nginx-proxy"
      - "DEBUG=true"
      - "ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory"
    tty: true
    restart: unless-stopped

  nginx-defaultsite:
    image: nginx:1.18.0-alpine
    volumes:
      - "${SITE}:/usr/share/nginx/html:ro"
    environment:
      - "VIRTUAL_HOST=${DOMAIN}.${TOP_LEVEL_DOMAIN}"
      - "LETSENCRYPT_HOST=${DOMAIN}.${TOP_LEVEL_DOMAIN}"
      - "LETSENCRYPT_EMAIL=info@${DOMAIN}.${TOP_LEVEL_DOMAIN}"
    restart: unless-stopped
```

I have confirmed that the files are created correctly in both ` letsencrypt-sidecar` and ` nginx-defaultsite` with the below:
```
docker exec -it letsencrypt-sidecar bash -c 'echo "Hello world!" > /usr/share/nginx/html/.well-known/acme-challenge/hello-world'

docker exec -it letsencrypt-sidecar /bin/bash bash -c 'cat /usr/share/nginx/html/.well-known/acme-challenge/hello-world'

docker exec -it nginx-defaultsite /bin/bash bash -c 'cat /usr/share/nginx/html/.well-known/acme-challenge/hello-world'
```
But when I attempt going to `http://mydomiain/.well-known/acme-challenge/hello-world` I get a 404.

Any insight into what I could be doing wrong would be greatly appreciated. I feel like I'm just missing one key component,...

**Comment by buchdag** [comment] 2020-05-21 07:52
Hi.

`/usr/share/nginx/html` should be shared between the `nginx-proxy` and `letsencrypt-nginx-proxy-companion` containers, not between the `letsencrypt-nginx-proxy-companion` and your website's container.

**Comment by sosukeinu** [comment] 2020-05-21 14:11
Perfect. That did it for me. I got confused because I figured the default site's html folder needed to be where the acme requests went. Thank you.

**Comment by buchdag** [comment] 2020-07-21 08:14
No updates from issue's creator in more than 60 days, closing.

**Closed by buchdag** 2020-07-21 08:14 UTC
Labels: Failing authorization, simp_le issue

**Comment by auchri** [comment] 2020-10-04 19:07
@buchdag @sosukeinu  I think I have the same issue, can you give me a hint what has to be done do resolve the issue?
